name: EtherealKits
version: '1.0'
main: gg.ethereallabs.etherealkits.EtherealKits
api-version: '1.21'
soft-depend: MMOItems
commands:
  kit:
    description: Main command for EtherealKits
    usage: /kit
    aliases: [etherealkits]